# Generic query templates
findAll: "SELECT * FROM ${table}"
findById: "SELECT * FROM ${table} WHERE id = :id"
create: "INSERT INTO ${table} (${fields}) VALUES (${values})"
update: "UPDATE ${table} SET ${setClause} WHERE id = :id"
delete: "DELETE FROM ${table} WHERE id = :id"

# Custom query templates
countAll: "SELECT COUNT(*) as count FROM ${table}"
findLatest: "SELECT * FROM ${table} ORDER BY id DESC LIMIT :limit"